# Path to oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(
  git
)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000
SAVEHIST=5000
setopt inc_append_history share_history

# Add your own stuff below

source "$HOME/dotfiles-next/zsh/aliases.zsh"
source "$HOME/rainbow/zsh/functions.zsh"
